name: Golang linter

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  golang-lint:
    name: golang-lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          install-mode: "binary"
