name: Go Mod Tidy Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Go Mod Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Tidy
        run: |
          make tidy check-git-clean
